feat: 添加交互式应用接口用于获取容器内交互式应用的连接配置
PKUHPC/scow-scheduler-adapter-interface pull request #14
Opened 2023-11-02 03:18 UTC by qhqhqhq

添加接口`GetConnectionConfig`, 用于获取交互式应用启动后的实际`host`,`port`,`password`等信息

2023-11-02 14:46 UTC, ddadaal requested changes

2023-11-02 14:46 UTC, ddadaal commented on protos/app.proto
> +  rpc GetConnectionConfig(GetConnectionConfigRequest) returns (GetConnectionConfigResponse);
这个名字我觉得有点不太贴合。Config一般是指人写的配置文件，这里是指的app运行中的信息，这个信息不是配置文件。我建议取名GetAppConnectionInfo。

2023-11-02 14:46 UTC, ddadaal commented on protos/app.proto
> +  optional string password = 3;
这个是vnc密码，就写名是vnc_password

2023-11-04 03:12 UTC, qhqhqhq commented on protos/app.proto
> +  optional string password = 3;
这个还包括web应用的密码, 我注释里写的有问题, 已修改

2023-11-05 06:11 UTC, ddadaal requested changes
按我的理解，这个API只有如下两种情况：
1. 直接使用SCOW中记录的信息：三个字符串都为空
2. 需要提供额外信息：必须提供host, port，可选提供password。

如果只有这两种情况，那么如果API返回`host`, `password`为空、`port`不为空的情况怎么办呢？

对不同情况分别创建不同的子message，然后使用`oneof`区分两种情况更能反应这个接口预期的行为。一种为直接使用scow里记录的信息，message不包含任何字段；一种为需要额外提供信息，其message包括`host`, `port`，以及optional的password。

2023-11-12 13:34 UTC, ddadaal requested changes

2023-11-12 13:34 UTC, ddadaal commented on protos/app.proto
> +  message NoAppConnectionInfo {}
这个message的名字我提议改为`UseScriptGenerated`，体现这个是采用作业启动时生成的信息这一点。

2023-11-12 14:00 UTC, ddadaal requested changes
改了之后先在SCOW中测试一下，没问题再request我合并

2023-11-13 13:54 UTC, ddadaal approved these changes

2023-11-13 13:54 UTC, merged