feat: 增加获取集群信息的接口 GetClusterInfo
PKUHPC/scow-scheduler-adapter-interface pull request #16
Opened 2023-11-13 03:36 UTC by OYX-1

增加获取集群信息的接口 GetClusterInfo

2023-11-13 14:02 UTC, ddadaal requested changes
- 已经有一个`GetClusterConfig`了，我的理解是Config是集群的静态配置，Info是集群运行时的状态，是这样吗？可以在注释里介绍一下两个的区别
- 建议所有和数量有关的变量以`???_count`格式取名，比如`running_job_count`

2023-11-14 02:19 UTC, OYX-1 commented on protos/config.proto
> +  string partition_name = 2;
我以为这里可以获取所有集群的所有分区信息，原来只能获取一个集群的信息。

2023-11-14 11:56 UTC, ddadaal requested changes

2023-11-14 11:56 UTC, ddadaal commented on protos/config.proto
> +  uint32 not_aviailable_gpu_count = 13;
available

2023-11-14 11:56 UTC, ddadaal commented on protos/config.proto
> +  repeated PartitionInfo partition_info = 2;
partitions，和Config统一把

2023-11-15 12:42 UTC, ddadaal approved these changes

2023-11-15 12:46 UTC, qhqhqhq approved these changes

2023-11-15 14:36 UTC, merged