feat: 分区管理与配置功能相关接口变更
PKUHPC/scow-scheduler-adapter-interface pull request #26
Opened 2024-05-28 07:52 UTC by piccaSun

2024-06-11 09:40 UTC, piccaSun commented
暂时没有合并要求，但是因为调度器和scow都基于此接口变动开发， 烦请优先帮忙确认上述变更是否需要修改 @ddadaal

2024-06-12 03:12 UTC, piccaSun commented on protos/account.proto
> +  repeated string partitions = 2;
是的，这块搞错了
修改为同时返回 账户对应的各个分区下封锁状态的详细信息
同时保留原有字段仍然表示账户在集群中的封锁状态（逻辑为当账户没有可用分区时 `blocked = true`， 其他情况为`false`）

同时对 `specified partitions`相关的传参也做出变更，现在`repeated string available_partitions`的形式在序列化反序列化中无法区分`undefined`和`[]`的情况，在`createAccount`等接口中不适用，重新修改了一下 请确认

2024-06-12 11:29 UTC, ddadaal commented on protos/account.proto
> +  // when the value is [], return BAD_REQUEST
如果是空，返回一个空的数组就好了，不需要报错

2024-06-12 11:29 UTC, ddadaal commented on protos/account.proto
>    bool blocked = 1;
写个注释解释一下新的blocked的含义

2024-06-12 11:29 UTC, ddadaal commented on protos/account.proto
> +  repeated string partitions = 2;
似乎没有必要区分undefined和[]的情况？

BlockAccount/UnblockAccount，默认情况为[]，则是封锁/解锁所有分区，和目前行为一致，参数不变的情况下行为不变，不影响接口兼容性。

QueryAccountBlockStatus，默认情况为[]，则是查询所有分区。

2024-06-12 11:33 UTC, ddadaal requested changes

2024-06-12 11:33 UTC, ddadaal commented on protos/account.proto
>    bool blocked = 1;
当queryed_partitions只包含一部分分区时，blocked的含义仍然是所有分区里有可用的就是false，还是只在可选分区里有可用的就是false？个人觉得后者比较好。

另外在现在可以部分封锁账户的条件下，blocked这个状态似乎没什么意义了，可以将其标为deprecate，之后找个机会删掉

2024-06-17 12:25 UTC, piccaSun commented on protos/account.proto
> +  repeated string partitions = 2;
已修改为不区分undefined和[]的情况
本来考虑在createAccount中必须区分，但是实际上createAccount只是在数据库建立关系，并没有实际的配置account的可用分区
所以确实如果protobuf中读到[]时，按全部分区处理就好

queryAccountBlockStatus的默认为[]时也为查找所有分区

2024-06-17 12:26 UTC, piccaSun commented on protos/account.proto
>    bool blocked = 1;
为了兼容现有接口暂时保留原有blocked状态，以为新的含义( ==> 只在可选分区里有可用的就是false )增加注释

2024-07-16 14:09 UTC, ddadaal requested changes

2024-07-16 14:09 UTC, ddadaal commented on protos/config.proto
> +  uint32 idle_cpu_core_counts = 6;
counts -> count

2024-07-16 14:09 UTC, ddadaal commented on protos/config.proto
> +  uint32 idle_mem = 9;
单位，类似total_mem_mb

2024-07-16 14:09 UTC, ddadaal commented on protos/config.proto
> +  repeated string nodes = 1;
每一项是node_name吗？如果是，改名node_names

2024-07-16 14:09 UTC, ddadaal commented on protos/job.proto
> +  optional string job_name = 7;
这个参数我建议放在Filter里，都是作为筛选用嘛。

2024-07-16 14:10 UTC, ddadaal commented on protos/config.proto
> +  repeated string nodes = 1;
现在SCOW里区分了不同的node，有node_name的概念吗？

2024-07-17 06:05 UTC, piccaSun commented on protos/config.proto
> +  repeated string nodes = 1;
跟杨老师确认了一下 @yangjie727 ，就是node_names的含义，类似partition的名字，在slurm中是节点的唯一标识符
此接口为提前预留的请求参数，如果请求参数中什么都不传递，就返回所有节点信息

2024-07-17 10:20 UTC, ddadaal approved these changes

2024-08-07 13:20 UTC, ddadaal requested changes

2024-08-08 01:36 UTC, piccaSun commented on protos/account.proto
> +  repeated AccountStatusInPartition account_blocked_details = 2;
不是的，只有这个返回值需要在非可选功能中也实现，因为这个blocked语义影响了提交作业的可选账户，目前如果不按照分区详细封锁状态返回可能会在可选账户列表时出现bug

2024-08-09 06:17 UTC, piccaSun commented on protos/account.proto
> +  repeated AccountStatusInPartition account_blocked_details = 2;
增加了版本注释，暂时以1.6.0版本做区分，请确认 @ddadaal

2024-08-09 13:55 UTC, ddadaal approved these changes

2024-09-19 13:07 UTC, ddadaal requested changes

2024-09-19 13:07 UTC, ddadaal commented on protos/config.proto
> +  // 3-17 Newly added parameters may not be returned
需要写清楚在有什么optional feature的情况下会返回这些字段

2024-09-19 14:29 UTC, piccaSun commented on protos/config.proto
> +  // 3-17 Newly added parameters may not be returned
已追加getClusterResponse兼容性变更的changeset
修改了注释中提到的对比1.6.0之前或之后版本，修改为对比1.7.0之前或之后的版本

2024-09-19 14:38 UTC, ddadaal approved these changes

2024-09-19 14:38 UTC, merged