feat: 增加节点信息获取接口等 1.6.0版本接口变更
PKUHPC/scow-scheduler-adapter-interface pull request #28
Opened 2024-07-24 08:06 UTC by piccaSun

// TODO scow/scheduler接口兼容处理变更，scow/scheduler联调

### 合并后接口版本 升级至 1.7.0

### 在config.proto中
1. 新增获取集群节点信息接口 GetClusterNodesInfo

### 在job.proto中
2. 在 getJobsRequest 中的 filter 中增加兼容型参数 job_id 和 job_name

2024-07-24 08:18 UTC, piccaSun commented
考虑实际需要发版情况及对应适配器的变更情况，还是需要拆分为1.6.0及1.7.0两个版本发布，请确认 @ddadaal

2024-07-24 16:01 UTC, ddadaal requested changes

2024-07-24 16:01 UTC, ddadaal commented on protos/config.proto
> +  string state = 3;
state应该有一些预设的值吧？如果所有state都是预设的，那就定义为enum；如果state可以接收适配器返回的随机的值，仍然返回string，但是需要用注释写明哪些是预设的值

2024-07-24 16:03 UTC, ddadaal commented on protos/config.proto
> +  string state = 3;
其他的没有问题

2024-07-25 02:03 UTC, usaveh commented on protos/config.proto
> +  string state = 3;
杨杰老师说适配器那边：预设的值不太确定
有很多种情况，而且这里面拿出来的值和sinfo看到的还不太一样

2024-07-25 13:52 UTC, ddadaal commented on protos/config.proto
> +  string state = 3;
适配器返回的值不确定，那SCOW或者其他的接口调用者应该如何使用这个字段？如果这个字段的值真是完全不确定，那么SCOW代码里不应该对这个字段返回的值做任何的处理，这个字段的使用方法就只有一个：直接给用户看。而对于**状态**这种看起来就应该是一种enum的值来说，这显示不合理。

我看到https://github.com/PKUHPC/SCOW/pull/1370 这个PR里SCOW会判断这个字段是不是`IDLE`或者`ALLOC`，那这就是预设值。不是说这个字段的值一定必须是enum，可以允许扩展，但是这个字段至少应该预定义一些值，这样SCOW才好对这个字段进行后续的处理。

2024-07-29 06:42 UTC, usaveh commented on protos/config.proto
> +  string state = 3;
目前前端只展示三种状态空闲 、可用。但是根据
https://slurm.schedmd.com/sinfo.html
![image](https://github.com/user-attachments/assets/17faca8e-9fc8-46a6-ad65-9d20634965d8)
他的状态理论上来说是这些状态加上这些状态的组合形式（可能两种或两种以上），所以枚举不完

2024-07-29 11:20 UTC, ddadaal commented on protos/config.proto
> +  string state = 3;
这层接口不只是给slurm做的，还兼容crane、k8s等其他不同的调度器，而不同的调度器的状态是不一样的，调度器的一大作用就是将不同的调度器返回的信息**统一**成同一套信息，使得SCOW在实现的时候可以不关心底层具体是什么调度器，而是直接使用接口的值。所以，这个接口需要返回什么样的值，应该从**SCOW需要什么信息**入手。

如果目前这个字段是直接使用slurm的状态，那么建议这样设计：

1. 定义一个`ClusterState`枚举，里面是**SCOW需要从调度器处获得的集群状态**。如果SCOW的功能期望这个节点可能会有多个状态，那么用`repeated`，否则就单值。SCOW所有需要对状态进行后续处理的（例如判断、筛选、国际化），都只能使用这个字段。调度器需要负责将底层的状态，转换为接口定义的状态的值。

```proto
// SCOW需要的状态
enum NodeState {
    UNKNOWN = 0,
    IDLE = 1, 
    // ...
}

// 如果只有一个状态，那么返回单值
NodeState node_state = ?

// 如果期望底层调度器返回多个状态，返回repeated
repeated NodeState node_states = ?
```
2. 加一个`string scheduler_node_state = ?`，直接返回底层调度器表示的集群的状态。对于这个字段，SCOW只能直接显示，不能做判断、筛选或者国际化。

2024-07-30 12:27 UTC, ddadaal approved these changes

2024-07-30 12:27 UTC, ddadaal commented
如果准备好了，可以ready for review并合并

2024-07-31 12:11 UTC, ddadaal approved these changes

2024-08-01 13:29 UTC, merged