参考portal的dashboard增加适配器GetClusterInfo属性和GetClusterNodesInfo接口
PKUHPC/scow-scheduler-adapter-interface pull request #36
Opened 2024-09-24 07:35 UTC by cuvalign

无法实现，待需求修改

2024-10-31 01:30 UTC, cuvalign commented
问题解决，进一步调试

2024-10-31 05:24 UTC, ddadaal requested changes

2024-10-31 05:24 UTC, ddadaal commented on protos/config.proto
> +  repeated string node_names = 1;
这样默认了node_name是全局唯一，不同cluster也不能有相同的node_name。是否应该加一个必选cluster参数，这样可以允许不同cluster有同名node？

2024-11-26 12:44 UTC, ddadaal approved these changes

2024-11-27 07:36 UTC, merged